
# url paths for data ingestion
credit_url: https://raw.githubusercontent.com/LeeMorinUCF/QMB6358F23/refs/heads/main/final_exam_2021/credit_bureau.csv
app_url: https://raw.githubusercontent.com/LeeMorinUCF/QMB6358F23/refs/heads/main/final_exam_2021/applications.csv
demo_url: https://raw.githubusercontent.com/LeeMorinUCF/QMB6358F23/refs/heads/main/final_exam_2021/demographic.csv


# model paths

model_path: artifacts/best_model.pkl





features:
 - ssn
 - zip_code
 - income
 - homeownership
 - purchases
 - credit_limit
 - fico
 - num_late
 - past_def
 - num_bankruptcy
 - avg_income
 - avg_income
 - density

#target variable

target: log_odds_utils


